sudo: false
language: php
php:
  - 5.5.9
  - 7.1

before_script:
  # Git clone the Drupal 8.4.x.
  - git clone --branch 8.4.x https://git.drupal.org/project/drupal.git
  # Copy the tests out of core.
  - cp -R drupal/core/tests .
  - test -f tests/Drupal/Tests/UnitTestCase.php

script:
  # Install our components through composer.
  - composer update --no-progress --no-suggest
  # We currently don't use core's phpunit.xml.dist or bootstrap.php. This is
  # because there are a lot of dependencies in there that won't be available to
  # us. As core gets better at this, we'll need to change this invocation.
  - ./vendor/bin/phpunit --bootstrap bootstrap.php tests/Drupal/Tests/Component/DependencyInjection/
  # Try again with the lowest version Composer can figure out.
  - composer update --prefer-lowest --no-progress --no-suggest
  - ./vendor/bin/phpunit --bootstrap bootstrap.php tests/Drupal/Tests/Component/DependencyInjection/
